DROP TABLE IF EXISTS forgot_passwords CASCADE;

CREATE TABLE forgot_passwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id UUID NOT NULL UNIQUE,
    code VARCHAR(10) NOT NULL, -- 6 dígitos, mas deixei margem pequena
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT pk_forgot_passwords PRIMARY KEY (id)
);

-- Garante que o user_id é ÚNICO (Regra de um código por usuário)
ALTER TABLE forgot_passwords
    ADD CONSTRAINT uc_forgot_passwords_user_id UNIQUE (user_id);

-- Chave Estrangeira ligando ao User
ALTER TABLE forgot_passwords
    ADD CONSTRAINT fk_forgot_passwords_users
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE;


  ALTER TABLE reservations
    ADD COLUMN completed BOOLEAN NOT NULL DEFAULT FALSE;